# Generated by Django 5.0.3 on 2024-03-14 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='ocation',
            new_name='location',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_birthday',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 14, 12, 32, 23, 484621, tzinfo=datetime.timezone.utc)),
        ),
    ]
