# Generated by Django 5.0.3 on 2024-03-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=750)),
                ('ocation', models.CharField(max_length=200)),
                ('meetup_time', models.DateTimeField(verbose_name='Meet up time')),
            ],
        ),
    ]
